openapi: 3.0.0
info:
  title: Fashion Store API
  description: This is a Smoothstack Fashion Store API (In Progress)
  contact:
    email: krissada.jindanupajit@smoothstack.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Jindanupajit-SS/FashionStore/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Product
  description: Product API
paths:
  /products:
    get:
      tags:
      - Product
      summary: searches product by id
      description: |
        By passing in the appropriate options, you can search for
        available products in the system
      operationId: searchProduct
      parameters:
      - name: productId
        in: path
        description: productId to search
        required: true
        style: simple
        explode: false
        schema:
          type: number
          format: int64
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "400":
          description: bad input parameter
        "404":
          description: not found
      x-swagger-router-controller: Product
    put:
      tags:
      - Product
      summary: adds a product
      description: Update a product in the system
      operationId: updateProduct
      requestBody:
        description: Inventory item to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "202":
          description: Accepted, item modified
        "400":
          description: invalid input, object invalid
        "409":
          description: ' Conflict, item not exists'
      x-swagger-router-controller: Product
    post:
      tags:
      - Product
      summary: adds a product
      description: Adds a product to the system
      operationId: addProduct
      requestBody:
        description: Inventory item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: ' Conflict, an existing item already exists'
      x-swagger-router-controller: Product
    delete:
      tags:
      - Product
      summary: delete a product
      description: Delete a product in the system
      operationId: deleteProduct
      parameters:
      - name: productId
        in: path
        description: productId to delete
        required: true
        style: simple
        explode: false
        schema:
          type: number
          format: int64
      responses:
        "204":
          description: No content, item deleted
        "400":
          description: invalid input, object invalid
        "409":
          description: ' Conflict, item not exists'
      x-swagger-router-controller: Product
components:
  schemas:
    Product:
      required:
      - productId
      - productName
      - productPrice
      type: object
      properties:
        productId:
          type: number
          format: int64
          example: 10001
        productPrice:
          type: number
          format: double
          example: 26.44
        productName:
          type: string
          example: Smoohstack Handbag (Medium)
        productDescription:
          type: string
          example: Medium Handbag with Smoothstack logo
        productCategory:
          $ref: '#/components/schemas/Category'
        productAttributeSet:
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
      example:
        productId: 10001
        productAttributeSet:
        - attributeId: 18701
          attributeValue: Red
          attributeName: Color
        - attributeId: 18701
          attributeValue: Red
          attributeName: Color
        productPrice: 26.44
        productName: Smoohstack Handbag (Medium)
        productDescription: Medium Handbag with Smoothstack logo
        productCategory:
          categoryName: Handbag
          categoryId: 10301
          categoryDescription: Handbag for Women
    Attribute:
      required:
      - attributeId
      - attributeName
      - attributeValue
      type: object
      properties:
        attributeId:
          type: number
          format: int64
          example: 18701
        attributeName:
          type: string
          example: Color
        attributeValue:
          type: string
          example: Red
      example:
        attributeId: 18701
        attributeValue: Red
        attributeName: Color
    Category:
      required:
      - categoryId
      - categoryName
      type: object
      properties:
        categoryId:
          type: number
          format: int64
          example: 10301
        categoryName:
          type: string
          example: Handbag
        categoryDescription:
          type: string
          example: Handbag for Women
      example:
        categoryName: Handbag
        categoryId: 10301
        categoryDescription: Handbag for Women
    TaxCode:
      required:
      - taxCodeAmount
      - taxCodeId
      - taxCodeName
      type: object
      properties:
        taxCodeId:
          type: number
          format: int64
          example: 10401
        taxCodeName:
          type: string
          example: VA State
        taxCodeAmount:
          type: number
          format: double
          example: 4
